package travail_pour_tous;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
  

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class LoginFen extends javax.swing.JFrame {

    Statement stmt;
    Connexion MaCon=new Connexion();
    protected String user;
    protected String password;
    /**
     * Creates new form Login
     */
    public LoginFen() {
        initComponents();
        this.setLocationRelativeTo(null);//centrer sur l'ecran
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_minimise = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLabel_close = new javax.swing.JLabel();
        jTabbedPane_login = new javax.swing.JTabbedPane();
        jPanel_chomeur = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton_connecter_chercheur = new javax.swing.JButton();
        enregistrer_chercheur = new javax.swing.JLabel();
        jPanel_etat = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        username_structure = new javax.swing.JTextField();
        password_structure = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        connecter_structure = new javax.swing.JButton();
        enregistrer_structure = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel_minimise.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_minimise.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimise.setText(" -");
        jLabel_minimise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimiseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Form");

        JLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_close.setText("X");
        JLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_minimise)
                .addGap(33, 33, 33)
                .addComponent(JLabel_close)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_minimise)
                    .addComponent(JLabel_close)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jTabbedPane_login.setBackground(new java.awt.Color(44, 62, 80));
        jTabbedPane_login.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPane_login.setFont(new java.awt.Font("Ink Free", 0, 12)); // NOI18N

        jPanel_chomeur.setBackground(new java.awt.Color(44, 62, 80));

        jLabel6.setBackground(new java.awt.Color(236, 240, 241));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mot de passe:");

        jLabel7.setBackground(new java.awt.Color(236, 240, 241));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nom d'utilisateur:");

        username.setBackground(new java.awt.Color(108, 122, 137));
        username.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(228, 241, 254));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        Password.setBackground(new java.awt.Color(108, 122, 137));
        Password.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(228, 241, 254));

        jButton3.setBackground(new java.awt.Color(192, 57, 43));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton_connecter_chercheur.setBackground(new java.awt.Color(34, 167, 240));
        jButton_connecter_chercheur.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton_connecter_chercheur.setForeground(new java.awt.Color(255, 255, 255));
        jButton_connecter_chercheur.setText("Connecter");
        jButton_connecter_chercheur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_connecter_chercheurActionPerformed(evt);
            }
        });

        enregistrer_chercheur.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        enregistrer_chercheur.setForeground(new java.awt.Color(255, 255, 255));
        enregistrer_chercheur.setText("Cliquer ici pour creer un nouveau compte");
        enregistrer_chercheur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enregistrer_chercheur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enregistrer_chercheurMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_chomeurLayout = new javax.swing.GroupLayout(jPanel_chomeur);
        jPanel_chomeur.setLayout(jPanel_chomeurLayout);
        jPanel_chomeurLayout.setHorizontalGroup(
            jPanel_chomeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_chomeurLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(enregistrer_chercheur)
                .addGap(155, 155, 155))
            .addGroup(jPanel_chomeurLayout.createSequentialGroup()
                .addGroup(jPanel_chomeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_chomeurLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel_chomeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_chomeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(Password)))
                    .addGroup(jPanel_chomeurLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton3)
                        .addGap(61, 61, 61)
                        .addComponent(jButton_connecter_chercheur)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel_chomeurLayout.setVerticalGroup(
            jPanel_chomeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_chomeurLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel_chomeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel_chomeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel_chomeurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton_connecter_chercheur))
                .addGap(18, 18, 18)
                .addComponent(enregistrer_chercheur)
                .addGap(41, 41, 41))
        );

        jTabbedPane_login.addTab("Chercheur", jPanel_chomeur);

        jPanel_etat.setBackground(new java.awt.Color(44, 62, 80));

        jLabel8.setBackground(new java.awt.Color(236, 240, 241));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mot de passe:");

        jLabel9.setBackground(new java.awt.Color(236, 240, 241));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nom d'utilisateur:");

        username_structure.setBackground(new java.awt.Color(108, 122, 137));
        username_structure.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        username_structure.setForeground(new java.awt.Color(228, 241, 254));
        username_structure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_structureActionPerformed(evt);
            }
        });

        password_structure.setBackground(new java.awt.Color(108, 122, 137));
        password_structure.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        password_structure.setForeground(new java.awt.Color(228, 241, 254));

        jButton5.setBackground(new java.awt.Color(192, 57, 43));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Annuler");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        connecter_structure.setBackground(new java.awt.Color(34, 167, 240));
        connecter_structure.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        connecter_structure.setForeground(new java.awt.Color(255, 255, 255));
        connecter_structure.setText("Connecter");
        connecter_structure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecter_structureActionPerformed(evt);
            }
        });

        enregistrer_structure.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        enregistrer_structure.setForeground(new java.awt.Color(0, 153, 255));
        enregistrer_structure.setText("Cliquer ici pour creer un nouveau compte");
        enregistrer_structure.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enregistrer_structure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enregistrer_structureMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_etatLayout = new javax.swing.GroupLayout(jPanel_etat);
        jPanel_etat.setLayout(jPanel_etatLayout);
        jPanel_etatLayout.setHorizontalGroup(
            jPanel_etatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_etatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(enregistrer_structure)
                .addGap(155, 155, 155))
            .addGroup(jPanel_etatLayout.createSequentialGroup()
                .addGroup(jPanel_etatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_etatLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel_etatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel_etatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username_structure, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(password_structure)))
                    .addGroup(jPanel_etatLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton5)
                        .addGap(61, 61, 61)
                        .addComponent(connecter_structure)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel_etatLayout.setVerticalGroup(
            jPanel_etatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_etatLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel_etatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(username_structure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel_etatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(password_structure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel_etatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(connecter_structure))
                .addGap(18, 18, 18)
                .addComponent(enregistrer_structure)
                .addGap(41, 41, 41))
        );

        jTabbedPane_login.addTab("Structure", jPanel_etat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jTabbedPane_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabel_closeMouseClicked
        System.exit(0);
        
    }//GEN-LAST:event_JLabel_closeMouseClicked

    private void jLabel_minimiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimiseMouseClicked
      this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimiseMouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton_connecter_chercheurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_connecter_chercheurActionPerformed
        user=username.getText();
        password=Password.getText();
        LoginBD lg=new LoginBD(user,password);
        lg.connecter();
        if(lg.statut_login==1){
     
           JOptionPane.showMessageDialog(null,"nom d'utilisateur et mot de passe correct");
          
           ChercheurFen rgf=new ChercheurFen();
           System.out.println("le user est"+user);
           rgf.setter(user);
           rgf.propriete();
           rgf.setVisible(true);
           rgf.pack();
           rgf.setLocationRelativeTo(null);
           rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           this.dispose();
          
            } 
            else{
                    JOptionPane.showMessageDialog(null,"mot de passe ou nom d'utilisateur incorrect");
                    Password.setText("");
                    username.setText("");  
            }
        
    }//GEN-LAST:event_jButton_connecter_chercheurActionPerformed

    private void enregistrer_chercheurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enregistrer_chercheurMouseClicked
 
        RegisterFormUsersFen rgf=new RegisterFormUsersFen();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_enregistrer_chercheurMouseClicked

    private void username_structureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_structureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_structureActionPerformed

    private void connecter_structureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecter_structureActionPerformed
        String user=username_structure.getText();
        String password=password_structure.getText();
        LoginBD lg=new LoginBD(user,password);
        lg.connecter_struct();
        if(lg.statut_login_struct==1){
     
            JOptionPane.showMessageDialog(null,"nom d'utilisateur et mot de passe correct");
           StructureFen rgf=new StructureFen();
           rgf.setter(user);
           rgf.propriete();
            rgf.setVisible(true);
            rgf.pack();
            rgf.setLocationRelativeTo(null);
            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
          
            } 
            else{
                    JOptionPane.showMessageDialog(null,"mot de passe ou nom d'utilisateur incorrect");
                    password_structure.setText("");
                    username_structure.setText("");  
            }        // TODO add your handling code here:
    }//GEN-LAST:event_connecter_structureActionPerformed

    private void enregistrer_structureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enregistrer_structureMouseClicked
        RegisterFormStructureFen rgf=new RegisterFormStructureFen();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();        
    }//GEN-LAST:event_enregistrer_structureMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_close;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton connecter_structure;
    private javax.swing.JLabel enregistrer_chercheur;
    private javax.swing.JLabel enregistrer_structure;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_connecter_chercheur;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_minimise;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_chomeur;
    private javax.swing.JPanel jPanel_etat;
    private javax.swing.JTabbedPane jTabbedPane_login;
    private javax.swing.JPasswordField password_structure;
    private javax.swing.JTextField username;
    private javax.swing.JTextField username_structure;
    // End of variables declaration//GEN-END:variables
}
